NAME = bsq

SRC = bsq.c ft_funct.c ft_read_map_files.c ft_valid_map_file.c ft_init_map.c \
		ft_find_max_square.c ft_print_map.c

CFLAGS = -Wall -Werror -Wextra

NAME:
	gcc ${CFLAGS} -o ${NAME} ${SRC}

all: ${NAME}

fclean:
	rm -f ${NAME}
